{{- if and .Values.backendUser.secrets (or .Values.backendUser.secrets.DB_PASSWORD) }}
apiVersion: v1
kind: Secret
metadata:
  name: backend-user-secret
  labels:
    {{ include "ecommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.backendUser.secrets.DB_PASSWORD }}
  DB_PASSWORD: {{ .Values.backendUser.secrets.DB_PASSWORD | quote }}
  {{- end }}
---
{{- end }}
