AWSTemplateFormatVersion: '2010-09-09'
Description: NAT Gateway

Parameters:

  PublicSubnet:
    Type: String
    
  ProjectName:
    Type: String
    
Resources:
  # NAT Gateway
  NatEip:
    Type: AWS::EC2::EIP
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    # DependsOn: IGWAttachment
    Properties:
      Domain: VPC
      Tags:
        - Key: Name
          Value: 
            Fn::Sub: "${ProjectName}-nat-eip"

  NatGateway:
    Type: AWS::EC2::NatGateway
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AllocationId:
        Fn::GetAtt:
          - NatEip
          - AllocationId
      SubnetId:
        Ref: PublicSubnet
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-nat-gw"

Outputs:

  NatGatewayId:
    Description: NAT Gateway ID
    Value:
      Ref: NatGateway


