AWSTemplateFormatVersion: '2010-09-09'
Description: NAT Gateway

Parameters:
  PublicSubnet:
    Type: String
  ProjectName:
    Type: String
  IGWAttachment:
    Type: String
  
    
Resources:
  NATEIP:
    Type: AWS::EC2::EIP
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    # DependsOn: IGWAttachment
    Properties:
      Domain: VPC
      Tags:
        - Key: Name
          Value: 
            Fn::Sub: "${ProjectName}-nat-eip"

  NatGateway:
    Type: AWS::EC2::NatGateway
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AllocationId:
        Fn::GetAtt:
          - NATEIP
          - AllocationId
      SubnetId:
        Ref: PublicSubnet
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-nat-gw"


