AWSTemplateFormatVersion: '2010-09-09'
Description: VPC + Public/Private Subnets

Parameters:

  ProjectName:
    Type: String

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16

  PublicSubnetCidr:
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnetCidr:
    Type: String
    Default: 10.0.2.0/24

  AvailabilityZone:
    Type: String
    Default: ap-southeast-1a


Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      CidrBlock:
        Ref: VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value:  # or Value: !Sub "${ProjectName}-vpc"
            Fn::Sub: "${ProjectName}-vpc"

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${ProjectName}-igw"

  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      VpcId: 
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  # Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      VpcId: 
        Ref: VPC
      CidrBlock:
        Ref: PublicSubnetCidr
      AvailabilityZone:
        Ref: AvailabilityZone
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: 
            Fn::Sub: "${ProjectName}-public-subnet"

  # Private Subnet:
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    DeletionPolicy: Delete 
    UpdateReplacePolicy: Delete
    Properties:
      VpcId: 
        Ref: VPC
      CidrBlock: 
        Ref: PrivateSubnetCidr
      AvailabilityZone:
        Ref: AvailabilityZone
      MapPublicIpOnLaunch: false
      Tags:
        - Key: name
          Value:
            Fn::Sub: "${ProjectName}-private-subnet"

Outputs:

  VpcId: 
    Description: VPC ID
    Value: 
      Ref: VPC

  InternetGatewayId:
    Description: Internet Gateway ID
    Value:
      Ref: InternetGateway

  PublicSubnetId:
    Description: Public Subnet ID
    Value: 
      Ref: PublicSubnet
      
  PrivateSubnetId:
    Description: Private Subnet ID
    Value:
      Ref: PrivateSubnet
