name: Terraform Check

on:
  push:
    branches:
      - main
      - develop
      - stage

  pull_request:
    branches:
      - main
      - develop
      - stage

  workflow_dispatch:

jobs:
  check:
    name: Lab2 Question2 - Validate & Security Scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: LAB1/terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: LAB1/terraform
          framework: terraform
          # có 1 số policies sẽ skip vì khi khi thêm vào ảnh hưởng tính sử dụng
          skip_check: CKV_AWS_88,CKV_AWS_130,CKV2_AWS_11,CKV2_AWS_41,CKV2_AWS_5,CKV_AWS_382,CKV_AWS_23,CKV_AWS_135,CKV_AWS_126,CKV_AWS_8,CKV_AWS_79